import type { Musician } from "@/lib/types";

export const musicians: Musician[] = [
  {
    id: "1",
    name: "Александр Потемкин",
    email: "pansanek@mail.com",
    phone: "+7 (916) 123-45-67",
    role: "musician",
    instruments: ["Гитара", "Вокал"],
    genres: ["Рок", "Метал"],
    skillLevel: 4,
    location: "Москва",
    avatar: "musician-1.png",
    bio: "Профессиональный гитарист с 10-летним опытом. Играю в стиле метал-рок.",
    aiTags: [
      { id: "1", text: "Ищу рок-группу", category: "collaboration" },
      { id: "2", text: "Готов к концертам", category: "activity" },
    ],
    status: "online",
    socialLinks: { vk: "pansanek" },
  },
  {
    id: "2",
    name: "Мария Сидорова",
    email: "maria@example.com",
    phone: "+7 (921) 234-56-78",
    role: "musician",
    instruments: ["Вокал", "Клавиши"],
    genres: ["Джаз", "Поп"],
    skillLevel: 5,
    location: "Санкт-Петербург",
    avatar: "musician-2.png",
    bio: "Джазовая вокалистка, выступаю в клубах города.",
    aiTags: [
      { id: "3", text: "Джем-сессии", category: "activity" },
      { id: "4", text: "Ищу пианиста", category: "collaboration" },
    ],
    status: "online",
    socialLinks: { vk: "maria_sid", youtube: "mariasidorova" },
  },
  {
    id: "3",
    name: "Дмитрий Козлов",
    email: "dmitry@example.com",
    phone: "+7 (903) 345-67-89",
    role: "venue_admin",
    instruments: ["Ударные"],
    genres: ["Рок", "Метал"],
    skillLevel: 4,
    location: "Москва",
    avatar: "musician-3.png",
    bio: 'Барабанщик с опытом студийной работы. Администратор студии "Звук".',
    aiTags: [
      { id: "5", text: "Студийная работа", category: "skill" },
      { id: "6", text: "Ищу группу", category: "collaboration" },
    ],
    status: "busy",
    socialLinks: {},
  },
  {
    id: "4",
    name: "Анна Волкова",
    email: "anna@example.com",
    phone: "+7 (843) 456-78-90",
    role: "musician",
    instruments: ["Скрипка", "Клавиши"],
    genres: ["Классика", "Электроника"],
    skillLevel: 5,
    location: "Казань",
    avatar: "musician-4.png",
    bio: "Классическая скрипачка, экспериментирую с электронной музыкой.",
    aiTags: [
      { id: "7", text: "Эксперименты со звуком", category: "goal" },
      { id: "8", text: "Онлайн-коллаборации", category: "collaboration" },
    ],
    status: "offline",
    socialLinks: { soundcloud: "anna_volkova", youtube: "annavolkova" },
  },
  {
    id: "5",
    name: "Иван Новиков",
    email: "ivan@example.com",
    phone: "+7 (916) 567-89-01",
    role: "musician",
    instruments: ["Бас-гитара"],
    genres: ["Фанк", "Джаз", "R&B"],
    skillLevel: 4,
    location: "Москва",
    avatar: "musician-5.png",
    bio: "Басист-фанкер, люблю грув и ритм.",
    aiTags: [
      { id: "9", text: "Фанк-джемы", category: "activity" },
      { id: "10", text: "Ищу духовиков", category: "collaboration" },
    ],
    status: "recording",
    socialLinks: { vk: "ivan_novikov" },
  },
  {
    id: "6",
    name: "Елена Морозова",
    email: "elena@example.com",
    phone: "+7 (812) 678-90-12",
    role: "teacher",
    instruments: ["Саксофон", "Флейта"],
    genres: ["Джаз", "Классика"],
    skillLevel: 5,
    location: "Санкт-Петербург",
    avatar: "musician-6.png",
    bio: "Профессиональный саксофонист, преподаю музыку более 8 лет.",
    aiTags: [
      { id: "11", text: "Преподавание", category: "skill" },
      { id: "12", text: "Биг-бэнд", category: "collaboration" },
    ],
    status: "online",
    socialLinks: { vk: "elena_moroz" },
    teacherProfile: {
      subjects: ["Саксофон", "Флейта", "Сольфеджио"],
      experience: 8,
      education:
        'СПбГК им. Римского-Корсакова, специальность "Духовые инструменты"',
      pricePerHour: 2500,
      lessonFormats: ["Офлайн", "Онлайн"],
      certificates: ["Диплом СПбГК", "Сертификат Berklee Online"],
      ageGroups: ["Дети", "Взрослые"],
    },
  },
  {
    id: "7",
    name: "Роман Захаров",
    email: "roman@example.com",
    phone: "+7 (495) 789-01-23",
    role: "producer",
    instruments: [],
    genres: ["Поп", "Хип-хоп", "R&B"],
    skillLevel: 5,
    location: "Москва",
    avatar: "musician-7.png",
    bio: "Независимый продюсер и промоутер. Работаю с молодыми артистами и организую концерты.",
    aiTags: [
      { id: "13", text: "Ищу новых артистов", category: "collaboration" },
      { id: "14", text: "Буккинг", category: "skill" },
    ],
    status: "online",
    socialLinks: {},
    producerProfile: {
      specialization: ["Продюсирование", "Промоутинг", "Буккинг"],
      genresWorkedWith: ["Поп", "Хип-хоп", "R&B", "Электроника"],
      artistsWorkedWith: "Более 20 независимых артистов за 5 лет",
      services: ["Продакшн", "Буккинг", "PR-поддержка", "Организация туров"],
      portfolioUrl: "roman-prod.ru",
    },
  },
  {
    id: "8",
    name: "Сергей Лебедев",
    email: "sergey@example.com",
    phone: "+7 (916) 890-12-34",
    role: "sound_engineer",
    instruments: [],
    genres: ["Рок", "Метал", "Электроника"],
    skillLevel: 5,
    location: "Москва",
    avatar: "musician-8.png",
    bio: "Звукорежиссёр с 12-летним опытом. Специализируюсь на записи и сведении рок-музыки.",
    aiTags: [
      { id: "15", text: "Сведение и мастеринг", category: "skill" },
      { id: "16", text: "Студийная запись", category: "activity" },
    ],
    status: "busy",
    socialLinks: { vk: "sergey_sound" },
    soundEngineerProfile: {
      specialization: ["Запись", "Сведение", "Мастеринг"],
      software: ["Pro Tools", "Logic Pro", "Waves"],
      hardwareSummary: "SSL консоль, мониторы Genelec, преампы Neve",
      genresWorkedWith: ["Рок", "Метал", "Электроника", "Поп"],
      studioAffiliation: 'Студия "Звук", Москва',
    },
  },
];
