import type { Venue } from "@/lib/types";
export const venues: Venue[] = [
  {
    id: "1",
    name: 'Студия "ILLUZN"',
    address: "Тимирязевская ул., 2/3",
    avatar: "venue-1.png",
    coordinates: [55.80812, 37.574265],
    city: "Москва",
    capacity: 10,
    type: "студия",
    equipment: ["Микрофоны Shure", "Микшер Yamaha", "Мониторы KRK"],
    photos: [],
    rating: 4.8,
    pricePerHour: 2500,
    description:
      "Профессиональная студия звукозаписи с опытными звукорежиссёрами.",
    phone: "+7 (495) 123-45-67",
    email: "info@studiailluzn.ru",
    workingHours: "10:00 — 22:00",
    socialLinks: { vk: "studio_illuzn" },
  },
  {
    id: "2",
    name: 'Репетиционная база "Stars"',
    address: "Рубцовская наб., 3, стр. 1",
    avatar: "venue-2.png",
    coordinates: [55.776593, 37.699948],
    city: "Москва",
    type: "репетиционная база",
    equipment: ["Барабаны Pearl", "Комбики Marshall", "Микрофоны"],
    photos: [],
    capacity: 10,
    rating: 4.5,
    pricePerHour: 1200,
    description: "Уютная репетиционная точка с полным бэклайном.",
    phone: "+7 (495) 234-56-78",
    email: "starsrep@mail.ru",
    workingHours: "12:00 — 24:00",
    socialLinks: { vk: "stars_rep" },
  },
  {
    id: "3",
    name: 'Клуб "Pure"',
    address: "ул. Покровка, 10, стр. 2",
    city: "Москва",
    avatar: "venue-3.png",
    coordinates: [55.758977, 37.644369],
    type: "концертный зал",
    equipment: ["Звук JBL", "Свет Chauvet", "Сцена 6x4м"],
    photos: [],
    capacity: 10,
    rating: 4.7,
    pricePerHour: 5000,
    description: "Джаз-клуб с камерной атмосферой на 100 человек.",
    phone: "+7 (812) 345-67-89",
    email: "purepurepure@club.ru",
    workingHours: "18:00 — 03:00",
    socialLinks: { vk: "pure_club", instagram: "pure_msc" },
  },
  {
    id: "4",
    name: 'Концертный зал "Аврора"',
    address: "Мансуровский пер., 10, стр. 2",
    coordinates: [55.740309, 37.593724],
    city: "Москва",
    type: "концертный зал",
    avatar: "venue-4.png",
    equipment: ["Звук L-Acoustics", "Профессиональный свет", "Сцена 12x8м"],
    photos: [],
    rating: 4.9,
    capacity: 10,
    pricePerHour: 15000,
    description:
      "Большой концертный зал на 500 мест с современным оборудованием.",
    phone: "+7 (843) 456-78-90",
    email: "aurora@concert.ru",
    workingHours: "09:00 — 23:00",
    socialLinks: { vk: "aurora_msc", website: "aurora-msc.ru" },
  },
];
