import type { Venue } from "@/lib/types";
export const venues: Venue[] = [
  {
    id: 1,
    name: 'Студия "Звук"',
    address: "ул. Тверская, 15",
    avatar: "venue-1.png",
    coordinates: [55.751244, 37.587093],
    city: "Москва",
    capacity: 10,
    type: "студия",
    equipment: ["Микрофоны Shure", "Микшер Yamaha", "Мониторы KRK"],
    photos: [],
    rating: 4.8,
    pricePerHour: 2500,
    description:
      "Профессиональная студия звукозаписи с опытными звукорежиссёрами.",
    phone: "+7 (495) 123-45-67",
    email: "info@studiazvuk.ru",
    workingHours: "10:00 — 22:00",
    socialLinks: { vk: "studia_zvuk" },
  },
  {
    id: 2,
    name: 'Репетиционная база "Гараж"',
    address: "ул. Арбат, 42",
    avatar: "venue-2.png",
    coordinates: [55.74221, 37.565128],
    city: "Москва",
    type: "репетиционная база",
    equipment: ["Барабаны Pearl", "Комбики Marshall", "Микрофоны"],
    photos: [],
    capacity: 10,
    rating: 4.5,
    pricePerHour: 1200,
    description: "Уютная репетиционная точка с полным бэклайном.",
    phone: "+7 (495) 234-56-78",
    email: "garazh@mail.ru",
    workingHours: "12:00 — 24:00",
    socialLinks: { vk: "garazh_rep" },
  },
  {
    id: 3,
    name: 'Клуб "Синий слон"',
    address: "Невский пр., 100",
    city: "Москва",
    avatar: "venue-3.png",
    coordinates: [55.707879, 37.587093],
    type: "концертный зал",
    equipment: ["Звук JBL", "Свет Chauvet", "Сцена 6x4м"],
    photos: [],
    capacity: 10,
    rating: 4.7,
    pricePerHour: 5000,
    description: "Джаз-клуб с камерной атмосферой на 100 человек.",
    phone: "+7 (812) 345-67-89",
    email: "blueelephant@club.ru",
    workingHours: "18:00 — 03:00",
    socialLinks: { vk: "blue_elephant_club", instagram: "blueelephant_spb" },
  },
  {
    id: 4,
    name: 'Концертный зал "Калисто"',
    address: "ул. Баумана, 25",
    coordinates: [55.773399, 37.633522],
    city: "Казань",
    type: "концертный зал",
    avatar: "venue-4.png",
    equipment: ["Звук L-Acoustics", "Профессиональный свет", "Сцена 12x8м"],
    photos: [],
    rating: 4.9,
    capacity: 10,
    pricePerHour: 15000,
    description:
      "Большой концертный зал на 500 мест с современным оборудованием.",
    phone: "+7 (843) 456-78-90",
    email: "aurora@concert.ru",
    workingHours: "09:00 — 23:00",
    socialLinks: { vk: "aurora_kazan", website: "aurora-kazan.ru" },
  },
];
